INSERT INTO categoria (nome) VALUES
("Desenvolvimento Web"),
("Banco de Dados"),
("Inteligência Artificial"),
("Programação Mobile"),
("Segurança da Informação"),
("DevOps"),
("Cloud Computing"),
("Internet das Coisas (IoT)"),
("Desenvolvimento de Jogos"),
("Big Data & Analytics"),
("Machine Learning"),
("Blockchain"),
("Arquitetura de Software"),
("Engenharia de Software"),
("UI/UX Design"),
("Frameworks Frontend"),
("Frameworks Backend"),
("APIs e Integrações"),
("Microservices"),
("Programação Funcional"),
("Programação Orientada a Objetos"),
("Automação de Testes"),
("Performance e Escalabilidade"),
("Edge Computing"),
("Realidade Aumentada e Virtual"),
("Chatbots e Assistentes Virtuais"),
("Low-Code e No-Code"),
("Desenvolvimento de APIs REST e GraphQL"),
("Segurança em Aplicações Web"),
("Gestão de Projetos de Software");

INSERT INTO artigo (titulo, conteudo, categoria_id) VALUES
("Introdução ao HTML5", "O HTML5 trouxe diversas melhorias para a estruturação de páginas web...", (SELECT id FROM categoria WHERE nome = "Desenvolvimento Web")),
("CSS Flexbox e Grid", "Aprenda a criar layouts modernos com Flexbox e Grid...", (SELECT id FROM categoria WHERE nome = "Desenvolvimento Web")),
("JavaScript: Fundamentos Essenciais", "Entenda os conceitos básicos da linguagem que domina a web...", (SELECT id FROM categoria WHERE nome = "Desenvolvimento Web")),
("Banco de Dados Relacional vs NoSQL", "Comparação entre bancos SQL e NoSQL e quando usar cada um...", (SELECT id FROM categoria WHERE nome = "Banco de Dados")),
("REST vs GraphQL: Qual escolher?", "Entenda as diferenças entre essas tecnologias de APIs...", (SELECT id FROM categoria WHERE nome = "APIs e Integrações")),
("Introdução ao Node.js", "O que é Node.js e por que ele é tão popular no desenvolvimento backend...", (SELECT id FROM categoria WHERE nome = "APIs e Integrações")),
("Autenticação com JWT no PHP", "Como implementar autenticação segura com JSON Web Tokens...", (SELECT id FROM categoria WHERE nome = "Segurança em Aplicações Web")),
("Laravel: Primeiros Passos", "Configurando e criando um projeto no Laravel do zero...", (SELECT id FROM categoria WHERE nome = "Frameworks Backend")),
("Vue.js: Criando um SPA", "Guia passo a passo para desenvolver uma Single Page Application...", (SELECT id FROM categoria WHERE nome = "Frameworks Frontend")),
("React vs Angular: Qual escolher?", "Comparação entre os dois frameworks mais populares do frontend...", (SELECT id FROM categoria WHERE nome = "Frameworks Frontend")),
("Segurança em Aplicações Web", "Dicas para proteger sua aplicação contra ataques comuns...", (SELECT id FROM categoria WHERE nome = "Segurança em Aplicações Web")),
("Docker para Desenvolvedores", "Aprenda a criar e gerenciar containers com Docker...", (SELECT id FROM categoria WHERE nome = "DevOps")),
("Microservices com Spring Boot", "Como estruturar um sistema baseado em microsserviços...", (SELECT id FROM categoria WHERE nome = "Microservices")),
("Testes Automatizados com Jest", "Melhores práticas para testar código JavaScript com Jest...", (SELECT id FROM categoria WHERE nome = "Automação de Testes")),
("Machine Learning com Python", "Introdução ao aprendizado de máquina utilizando Python...", (SELECT id FROM categoria WHERE nome = "UI/UX Design")),
("Criando um Chatbot com IA", "Passo a passo para desenvolver um chatbot inteligente...", (SELECT id FROM categoria WHERE nome = "Chatbots e Assistentes Virtuais")),
("O que é Blockchain?", "Entenda a tecnologia por trás do Bitcoin e outras criptomoedas...", (SELECT id FROM categoria WHERE nome = "Blockchain")),
("Big Data: O que você precisa saber", "Principais conceitos e ferramentas para análise de Big Data...", (SELECT id FROM categoria WHERE nome = "Big Data & Analytics")),
("Desenvolvendo APIs com FastAPI", "Como criar APIs rápidas e eficientes com FastAPI...", (SELECT id FROM categoria WHERE nome = "APIs e Integrações")),
("NoSQL com MongoDB", "Introdução ao banco de dados NoSQL MongoDB...", (SELECT id FROM categoria WHERE nome = "Banco de Dados")),
("GraphQL na Prática", "Como utilizar GraphQL para criar APIs eficientes...", (SELECT id FROM categoria WHERE nome = "APIs e Integrações")),
("Kubernetes para Iniciantes", "Gerenciando containers em escala com Kubernetes...", (SELECT id FROM categoria WHERE nome = "DevOps")),
("Scrum e Metodologias Ágeis", "Entenda como funciona o Scrum e as práticas ágeis...", (SELECT id FROM categoria WHERE nome = "Gestão de Projetos de Software")),
("Desenvolvimento Mobile com Flutter", "Criando aplicativos multiplataforma com Flutter...", (SELECT id FROM categoria WHERE nome = "Programação Mobile")),
("IoT: Internet das Coisas", "Explorando o mundo da Internet das Coisas...", (SELECT id FROM categoria WHERE nome = "Internet das Coisas (IoT)")),
("Cybersecurity: Como se proteger online", "Boas práticas para aumentar a segurança na internet...", (SELECT id FROM categoria WHERE nome = "Segurança da Informação")),
("Criando um E-commerce do zero", "Passos essenciais para desenvolver uma loja virtual...", (SELECT id FROM categoria WHERE nome = "Desenvolvimento Web"));